### PR TITLE
fix Comparison typo

### PR DESCRIPTION
**Pull request by ccostin93**
- fix typo in ExcludeComparis**i**ons -> ExcludeComparisons

### CODE REVIEW

**Comment by nikialeksey** [comment]
@ccostin93 Thanks for the request! Please, update the minor library version in the `./lib/build.gradle` to `0.3.3`

**Comment by ccostin93** [comment]
@nikialeksey Done.

**Comment by nikialeksey** [comment]
@ccostin93 Please, solve the conflicts and there is one more thing: keep the branches from merge commits, use rebase instead

**Comment by ccostin93** [comment]
@nikialeksey Done. I also changed the version to 0.3.6 since the current is 0.3.5

**Comment by nikialeksey** [comment]
@ccostin93 Thanks!

**Pull request merged**
